// GENERATED by tokens/generate.mjs — do not edit. v3.0.0
import SwiftUI

enum JSType {
    static let t0: CGFloat = 9   // caps label — band pill, evidence key, section label
    static let t1: CGFloat = 11   // meta — chip, date, org line
    static let t2: CGFloat = 13   // body — descriptions, buttons, UI
    static let t3: CGFloat = 15.5   // emphasis — nav rows, lede
    static let t4: CGFloat = 18.5   // card title — serif
    static let t5: CGFloat = 22   // screen title — serif
    static let t6: CGFloat = 26   // page title — serif
    static let t7: CGFloat = 31.5   // hero — serif
    static let t8: CGFloat = 37.5   // display — desktop screen title
    static let t9: CGFloat = 44.5   // display — desktop page title
    static let t10: CGFloat = 53.5   // display — desktop hero
    static let t11: CGFloat = 64   // display — wide hero
    static let t12: CGFloat = 76.5   // display — widest hero
}

enum JSSpace {
    static let s0: CGFloat = 2
    static let s1: CGFloat = 4
    static let s2: CGFloat = 8
    static let s3: CGFloat = 12
    static let s4: CGFloat = 16
    static let s5: CGFloat = 20
    static let s6: CGFloat = 24
    static let s7: CGFloat = 32
    static let s8: CGFloat = 40
    static let s9: CGFloat = 48
    static let s10: CGFloat = 56
    static let s11: CGFloat = 64
    static let s12: CGFloat = 72
    static let s13: CGFloat = 80
    static let s14: CGFloat = 96
    static let s15: CGFloat = 128
}

enum JSRadius {
    static let chip: CGFloat = 4
    static let inner: CGFloat = 10
    static let card: CGFloat = 16
    static let sheet: CGFloat = 22
    static let pill: CGFloat = 999
}

extension Color {
    init(hex: UInt32) {
        self.init(.sRGB, red: Double((hex >> 16) & 0xFF)/255,
                  green: Double((hex >> 8) & 0xFF)/255,
                  blue: Double(hex & 0xFF)/255, opacity: 1)
    }
}

enum JSBands {
    static let auto = Color(hex: 0x3E954D)
    static let ping = Color(hex: 0x617AD1)
    static let unsure = Color(hex: 0xB86B03)
    static let nearmiss = Color(hex: 0x7D7D97)
    static let autoDark = Color(hex: 0x7AC683)
    static let pingDark = Color(hex: 0x93ADFF)
    static let unsureDark = Color(hex: 0xE89F59)
    static let nearmissDark = Color(hex: 0xAEAFC7)
    static let autoLabel = Color(hex: 0x225B2C)
    static let pingLabel = Color(hex: 0x394981)
    static let unsureLabel = Color(hex: 0x713F00)
    static let nearmissLabel = Color(hex: 0x4B4B5C)
    static let autoLabelDark = Color(hex: 0x92D098)
    static let pingLabelDark = Color(hex: 0xA4BBFF)
    static let unsureLabelDark = Color(hex: 0xECB078)
    static let nearmissLabelDark = Color(hex: 0xBBBCD0)
    static let autoFill = Color(hex: 0xE7F4E8)
    static let pingFill = Color(hex: 0xEAF0FF)
    static let unsureFill = Color(hex: 0xFBEDE2)
    static let nearmissFill = Color(hex: 0xEFF0F4)
    static let autoFillDark = Color(hex: 0x223424)
    static let pingFillDark = Color(hex: 0x272E42)
    static let unsureFillDark = Color(hex: 0x3D2B1A)
    static let nearmissFillDark = Color(hex: 0x2E2E34)
    static let litByBand: [String: Int] = ["auto": 8, "ping": 6, "unsure": 5, "nearmiss": 3]
}

// score -> band. CONFIRMED from the code 2026-09-21. The scorer emits
// `fit` ONLY and every client derives, so this must match web and
// Android exactly. It is generated for that reason.
enum JSBand {
    static let auto = 80
    static let ping = 70
    static let unsure = 55
    static func of(_ fit: Int) -> String {
        if fit >= auto { return "auto" }
        if fit >= ping { return "ping" }
        if fit >= unsure { return "unsure" }
        return "nearmiss"
    }
}

// SwiftUI's `response` IS the natural period, so it equals the CSS duration.
enum JSMotion {
    static let snap = Animation.spring(response: 0.180, dampingFraction: 0.72)
    static let settle = Animation.spring(response: 0.340, dampingFraction: 1)
    static let arrive = Animation.spring(response: 0.520, dampingFraction: 0.62)
    static let exit = Animation.easeIn(duration: 0.160)
}

enum JSRose {
    static let ring: CGFloat = 11;  static let box: CGFloat = 12
    static let r0: CGFloat = 2.275;  static let dr: CGFloat = 0.2944;  static let count = 8
    static let emptyAlpha = 0.14;  static let emptyScale: CGFloat = 0.55
}
