// GENERATED by tokens/generate.mjs — do not edit. v3.0.0
package page.jobscout.design

import androidx.compose.animation.core.*
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.unit.dp
import androidx.compose.ui.unit.sp

object Type {
    val t0 = 9.sp   // caps label — band pill, evidence key, section label
    val t1 = 11.sp   // meta — chip, date, org line
    val t2 = 13.sp   // body — descriptions, buttons, UI
    val t3 = 15.5.sp   // emphasis — nav rows, lede
    val t4 = 18.5.sp   // card title — serif
    val t5 = 22.sp   // screen title — serif
    val t6 = 26.sp   // page title — serif
    val t7 = 31.5.sp   // hero — serif
}

object Space {
    val s0 = 2.dp
    val s1 = 4.dp
    val s2 = 8.dp
    val s3 = 12.dp
    val s4 = 16.dp
    val s5 = 20.dp
    val s6 = 24.dp
    val s7 = 32.dp
}

object Radius {
    val chip = 4.dp
    val inner = 10.dp
    val card = 16.dp
    val sheet = 22.dp
    val pill = 999.dp
}

object Bands {
    val auto = Color(0xFF3E954D)
    val ping = Color(0xFF617AD1)
    val unsure = Color(0xFFB86B03)
    val nearmiss = Color(0xFF7D7D97)
    val autoDark = Color(0xFF7AC683)
    val pingDark = Color(0xFF93ADFF)
    val unsureDark = Color(0xFFE89F59)
    val nearmissDark = Color(0xFFAEAFC7)
    val autoLabel = Color(0xFF225B2C)
    val pingLabel = Color(0xFF394981)
    val unsureLabel = Color(0xFF713F00)
    val nearmissLabel = Color(0xFF4B4B5C)
    val autoLabelDark = Color(0xFF92D098)
    val pingLabelDark = Color(0xFFA4BBFF)
    val unsureLabelDark = Color(0xFFECB078)
    val nearmissLabelDark = Color(0xFFBBBCD0)
    val autoFill = Color(0xFFE7F4E8)
    val pingFill = Color(0xFFEAF0FF)
    val unsureFill = Color(0xFFFBEDE2)
    val nearmissFill = Color(0xFFEFF0F4)
    val autoFillDark = Color(0xFF223424)
    val pingFillDark = Color(0xFF272E42)
    val unsureFillDark = Color(0xFF3D2B1A)
    val nearmissFillDark = Color(0xFF2E2E34)
    val litByBand = mapOf("auto" to 8, "ping" to 6, "unsure" to 5, "nearmiss" to 3)
}

// Compose cannot consume linear(). Do NOT eyeball an equivalent and do NOT
// substitute Compose's named stiffness constants — the durations stop
// matching and the clients drift. Derived from the same parameters:
// w = 2*PI / durationSeconds ; stiffness = w^2
object Motion {
    val snap = spring<Float>(dampingRatio = 0.72f, stiffness = 1218f)   // 180ms
    val settle = spring<Float>(dampingRatio = 1f, stiffness = 342f)   // 340ms
    val arrive = spring<Float>(dampingRatio = 0.62f, stiffness = 146f)   // 520ms
    val exit = tween<Float>(160, easing = CubicBezierEasing(0.4f, 0f, 1f, 1f))
}

object Rose {
    const val RING = 11f; const val BOX = 12f
    const val R0 = 2.275f;  const val DR = 0.2944f;  const val COUNT = 8
    const val EMPTY_ALPHA = 0.14f; const val EMPTY_SCALE = 0.55f
}
