CREATE TABLE IF NOT EXISTS demo_runs (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  ip_hash TEXT NOT NULL,
  ts_ms INTEGER NOT NULL,
  day TEXT NOT NULL,
  tokens_in INTEGER NOT NULL DEFAULT 0,
  tokens_out INTEGER NOT NULL DEFAULT 0,
  cost_usd REAL NOT NULL DEFAULT 0
);
CREATE INDEX IF NOT EXISTS idx_runs_ip ON demo_runs (ip_hash, ts_ms);
CREATE INDEX IF NOT EXISTS idx_runs_day ON demo_runs (day);
CREATE TABLE IF NOT EXISTS feed (day TEXT PRIMARY KEY, payload TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS cached_showcase (id INTEGER PRIMARY KEY AUTOINCREMENT, payload TEXT NOT NULL);
