#!/usr/bin/env node
/**
 * gen_kit_js.mjs — the web's form filler IS the phone's. site/kit-fill.js is generated from
 * Kit.kt's FILL_JS and ATTACH_JS, never edited by hand, so the bookmark button on the web and
 * the in-app filler on Android cannot drift apart.
 *
 * Ken, 2026-10-01: "Yes, build the bookmark button too" (desktop Chrome: one click on the
 * employer's own form fills it from the JobScout tab that opened it).
 *
 *   node tools/gen_kit_js.mjs           write site/kit-fill.js
 *   node tools/gen_kit_js.mjs --check   fail if site/kit-fill.js is not what Kit.kt says
 */
import { readFileSync, writeFileSync } from "node:fs";
const kt = readFileSync(new URL("../android/app/src/main/java/trade/tbot/jobscout/Kit.kt", import.meta.url), "utf8");
const js = name => {
  const at = kt.indexOf(`${name} = """`);
  if (at < 0) throw new Error(`${name} not found in Kit.kt`);
  const i = at + name.length + 7;
  return kt.slice(i, kt.indexOf('"""', i)).trim();
};
const out = "/* GENERATED by tools/gen_kit_js.mjs from Kit.kt (FILL_JS, ATTACH_JS). Do not edit: edit Kit.kt and regenerate. */\n" +
  `window.JSKIT_FILL = ${JSON.stringify(js("FILL_JS"))};\n` +
  `window.JSKIT_ATTACH = ${JSON.stringify(js("ATTACH_JS"))};\n`;
const path = new URL("../site/kit-fill.js", import.meta.url);
if (process.argv.includes("--check")) {
  let now = ""; try { now = readFileSync(path, "utf8"); } catch {}
  const ok = now.replace(/\r\n/g, "\n") === out;
  console.log(ok ? "VERDICT: PASS — the web's filler is the phone's, byte for byte"
                 : "VERDICT: FAIL — site/kit-fill.js differs from Kit.kt: run node tools/gen_kit_js.mjs");
  process.exit(ok ? 0 : 1);
}
writeFileSync(path, out);
console.log("wrote site/kit-fill.js");
